controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: fr|br|go
    defaults:
        _locale: fr

redirect:
    path: /
    controller: App\Controller\RedirectController::redirectToLocale

# Redirection pour le gallo non disponible
locale_not_available:
    path: /locale-not-available
    controller: App\Controller\LocaleController::localeNotAvailable